[package]
name = "memory-models"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
image = { version = "=0.24.9", default-features = false, features = ["gif", "jpeg", "png", "webp"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10.9"
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
